#!/usr/bin/env python
# encoding: utf-8

import logging

# Set up the logger
logger = logging.getLogger('pkgs')
# Use a console handler, set it to debug by default
logger_ch = logging.StreamHandler()
logger.setLevel(logging.INFO)
log_formatter = logging.Formatter(('%(asctime)s %(levelname)s:%(process)s'
                                   ' %(lineno)s:%(module)s:%(funcName)s()'
                                   ' %(message)s'))
logger_ch.setFormatter(log_formatter)
logger.addHandler(logger_ch)


import argparse
# import tornado.ioloop

# from lib import Search, Install
# from lib import PkgsIOLoop

import cmds

parser = argparse.ArgumentParser(
    "pkgs",
    description=("Package Yourself")
)

# parser.add_argument('-t', '--test',
#                     default='default_value',
#                     help=("Some nice help for this option")
#                     )

parser.add_argument('-d',
                    '--debug',
                    default=False, action='store_true',
                    help=("Enable debug output and debug run mode")
                    )

parser.add_argument('-c',
                    '--config',
                    default=None,
                    help=("Specify a config file location.")
                    )

# # positional argument
# parser.add_argument('search',
#                     default=None,
#                     # nargs="?",
#                     nargs=1,
#                     help=("Search for a package/repo by name")
#                     )


def main():
    # Install our own IOLoop instance
    # PkgsIOLoop().install()

    # Sub parsers.
    sub_parser = parser.add_subparsers(help=("pkgs commands"))
    cmds.build_cmds(sub_parser)

    args = parser.parse_args()
    if args.debug:
        logger.setLevel(logging.DEBUG)

    logger.debug("args: %s", args)

    import conf
    conf.load_settings(args.config)

    logger.debug("settings: %s", conf.settings)

    if hasattr(args, 'func'):
        return args.func(args)

    parser.print_help()
# main()

if __name__ == '__main__':
    main()
