.DEFAULT: install
.PHONY: install uninstall clean realclean
pkg=jhome

install:
	./install.sh

# uninstall:
#     sudo rm -frv /usr/local/heroku

# clean:
#     cd $(pkg); make clean

# realclean:
#     rm -fr $(pkg)

