.DEFAULT: install
.PHONY: install uninstall clean realclean
pkg=heroku-client

install:
	./install.sh

uninstall:
	sudo rm -frv /usr/local/heroku

check:
	@echo "Nothing to check"

# clean:
#     cd $(pkg); make clean

# realclean:
#     rm -fr $(pkg)
