#!/usr/bin/env python
# encoding: utf-8

import logging

# Set up the logger
logger = logging.getLogger('upkg')
cmd_logger = logging.getLogger('command')
# Use a console handler, set it to debug by default
logger_ch = logging.StreamHandler()
logger.setLevel(logging.INFO)
log_formatter = logging.Formatter(('%(asctime)s %(levelname)s:%(process)s'
                                   ' %(lineno)s:%(module)s:%(funcName)s()'
                                   ' %(message)s'))
logger_ch.setFormatter(log_formatter)
logger.addHandler(logger_ch)


import argparse
import os
import shutil
# import tornado.ioloop

# from lib import Search, Install
# from lib import UpkgIOLoop

import cmds
import services

parser = argparse.ArgumentParser(
    "upkg",
    description=("Package Yourself")
)

parser.add_argument('-d',
                    '--debug',
                    default=False, action='store_true',
                    help=("Enable debug output and debug run mode")
                    )

parser.add_argument('-c',
                    '--config',
                    default=None,
                    help=("Specify a config file location.")
                    )


def main():
    # Install our own IOLoop instance
    # UpkgIOLoop().install()

    # register our services
    services.register_services()

    # Sub parsers.
    sub_parser = parser.add_subparsers(help=("upkg commands"))
    cmds.build_cmds(sub_parser)

    args = parser.parse_args()
    if args.debug:
        logger.setLevel(logging.DEBUG)
        cmd_logger.setLevel(logging.DEBUG)

    logger.debug("args: %s", args)

    import conf
    settings = conf.load_settings(args.config)

    # make sure the db directory exists
    if not os.path.exists(settings.dbs_path):
        shutil.os.makedirs(settings.dbs_path)

    logger.debug("settings: %s", conf.settings)

    if hasattr(args, 'func'):
        return args.func(args)

    parser.print_help()
# main()

if __name__ == '__main__':
    main()
